# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=inventory_user
spring.datasource.password=inventory_pass

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Puerto del servidor
server.port=8080